update=16/04/2017 19:50:09
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[eeschema]
version=1
LibDir=../../../[Resources]/KiCAD Libraries/SparkFun-Kicad-Libraries;../../../[Resources]/KiCAD Libraries
[eeschema/libraries]
LibName1=BufuBox-rescue
LibName2=power
LibName3=device
LibName4=transistors
LibName5=conn
LibName6=linear
LibName7=regul
LibName8=74xx
LibName9=cmos4000
LibName10=adc-dac
LibName11=memory
LibName12=xilinx
LibName13=microcontrollers
LibName14=dsp
LibName15=microchip
LibName16=analog_switches
LibName17=motorola
LibName18=texas
LibName19=intel
LibName20=audio
LibName21=interface
LibName22=digital-audio
LibName23=philips
LibName24=display
LibName25=cypress
LibName26=siliconi
LibName27=opto
LibName28=atmel
LibName29=contrib
LibName30=valves
LibName31=E:/Dropbox/[Resources]/KiCAD Libraries/toolbox
LibName32=E:/Dropbox/[Resources]/KiCAD Libraries/SparkFun-Kicad-Libraries/adafruit
LibName33=E:/Dropbox/[Resources]/KiCAD Libraries/SparkFun-Kicad-Libraries/GeekAmmo
LibName34=E:/Dropbox/[Resources]/KiCAD Libraries/SparkFun-Kicad-Libraries/LilyPad-Wearables
LibName35=E:/Dropbox/[Resources]/KiCAD Libraries/SparkFun-Kicad-Libraries/SparkFun-Aesthetics
LibName36=E:/Dropbox/[Resources]/KiCAD Libraries/SparkFun-Kicad-Libraries/SparkFun-AnalogIC
LibName37=E:/Dropbox/[Resources]/KiCAD Libraries/SparkFun-Kicad-Libraries/SparkFun-Boards
LibName38=E:/Dropbox/[Resources]/KiCAD Libraries/SparkFun-Kicad-Libraries/SparkFun-Capacitors
LibName39=E:/Dropbox/[Resources]/KiCAD Libraries/SparkFun-Kicad-Libraries/SparkFun-Connectors
LibName40=E:/Dropbox/[Resources]/KiCAD Libraries/SparkFun-Kicad-Libraries/SparkFun-DigitalIC
LibName41=E:/Dropbox/[Resources]/KiCAD Libraries/SparkFun-Kicad-Libraries/SparkFun-DiscreteSemi
LibName42=E:/Dropbox/[Resources]/KiCAD Libraries/SparkFun-Kicad-Libraries/SparkFun-Displays
LibName43=E:/Dropbox/[Resources]/KiCAD Libraries/SparkFun-Kicad-Libraries/SparkFun-Electromechanical
LibName44=E:/Dropbox/[Resources]/KiCAD Libraries/SparkFun-Kicad-Libraries/SparkFun-FreqCtrl
LibName45=E:/Dropbox/[Resources]/KiCAD Libraries/SparkFun-Kicad-Libraries/SparkFun-LED
LibName46=E:/Dropbox/[Resources]/KiCAD Libraries/SparkFun-Kicad-Libraries/SparkFun-Passives
LibName47=E:/Dropbox/[Resources]/KiCAD Libraries/SparkFun-Kicad-Libraries/SparkFun-PowerIC
LibName48=E:/Dropbox/[Resources]/KiCAD Libraries/SparkFun-Kicad-Libraries/SparkFun-Resistors
LibName49=E:/Dropbox/[Resources]/KiCAD Libraries/SparkFun-Kicad-Libraries/SparkFun-Retired
LibName50=E:/Dropbox/[Resources]/KiCAD Libraries/SparkFun-Kicad-Libraries/SparkFun-RF
LibName51=E:/Dropbox/[Resources]/KiCAD Libraries/SparkFun-Kicad-Libraries/SparkFun-Sensors
LibName52=E:/Dropbox/[Resources]/KiCAD Libraries/SparkFun-Kicad-Libraries/Teensy_3_and_LC_Series_Boards_v1.1
LibName53=E:/Dropbox/[Resources]/KiCAD Libraries/SparkFun-Kicad-Libraries/User-Submitted
